# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='isAdmin',
        ),
    ]
