# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-26 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('release', '0005_auto_20190326_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='nginx_conf',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='nginx配置'),
        ),
        migrations.AlterField(
            model_name='project',
            name='note',
            field=models.CharField(blank=True, default=None, max_length=2000, null=True, verbose_name='项目介绍'),
        ),
    ]
